<?php
/**
 * Implement hook_menu(), just to intercept the request for this query_api.
 */


// load http method hooks
// drupal_get_path($type, $name)
$path = drupal_get_path('module', 'rest_article');

require_once($path.'/processors/rest_article.get');

// require_once($path.'/processors/rest_article.post');
// require_once($path.'/processors/rest_article.delete');
// require_once($path.'/processors/rest_article.put');

function rest_article_menu() {
	// module_load_include($type, $module, $name = NULL)
	module_load_include('inc', 'rest_article', 'rest_article.get');
	
	$items = array();

	$items['admin/rest/article/test'] = array(
		'title' => 'REST API article endpoint test page',

		'page callback' => 'rest_article_test',
		'access arguments' => array('dashboard'),
	);

	return $items;
}

function rest_article_test() {
	return 'rest article admin';
}