<?php
/**
 * Implement hook_menu(), just to intercept the request for this query_api.
 */


// load http method hooks
// drupal_get_path($type, $name)
$path = drupal_get_path('module', 'rest_entity');

require_once($path.'/processors/rest_entity.get');
require_once($path.'/processors/rest_entity.post');
require_once($path.'/processors/rest_entity.delete');
require_once($path.'/processors/rest_entity.put');

function rest_entity_menu() {
	// module_load_include($type, $module, $name = NULL)
	module_load_include('inc', 'rest_entity', 'rest_entity.get');
	
	$items = array();

	$items['admin/rest/node'] = array(
		'title' => 'REST API node endpoint admin',
		'type' => MENU_LOCAL_TASK,

		'page callback' => 'rest_entity_admin',
		'access arguments' => array('dashboard'),
	);




	return $items;
}

function rest_entity_admin() {
	return 'rest node admin';
}